apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql-container
        image: mcr.microsoft.com/mssql/server:2022-CU11-ubuntu-20.04
        env:
          - name: MSSQL_PID
            value: "Developer"
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_AGENT_ENABLED
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql-sa-secret
                key: MSSQL_SA_PASSWORD