apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mssql-daemonset
spec:
  selector:
    matchLabels:
      name: mssql-pod
  template:
    metadata:
      labels:
        name: mssql-pod
    spec:
      containers:
      - name: mssql-container
        image: mcr.microsoft.com/mssql/server:2022-CU11-ubuntu-20.04
        env:
          - name: MSSQL_PID
            value: "Developer"
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_AGENT_ENABLED
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql-sa-password
                key: MSSQL_SA_PASSWORD