apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mssql-storage
provisioner: kubernetes.io/portworx-volume
parameters:
  openstorage.io/auth-secret-name: px-user-token
  openstorage.io/auth-secret-namespace: kube-system
  allowVolumeExpansion: "true"
  repl: "3"